# Generated by Django 4.2.16 on 2024-10-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_deposit_id_alter_withdrawal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
