# Generated by Django 4.2.16 on 2024-10-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_deposit_validated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
