# Generated by Django 4.2.16 on 2024-11-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_passwordresettokencode_delete_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
